### ISSUE TITLE
[1.3.0] BUG   worker exits from panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jicki** [jmcgrath207/k8s-ephemeral-storage-metrics#44]
``` 
2023/11/27 07:45:46.596630 [ants]: worker exits from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 93 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run.func1.1()
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.9.0/worker_func.go:56 +0x85
panic({0x146e960?, 0x2316f00?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
main.setMetrics({0xc000048e40, 0x30})
        /code/main.go:259 +0xfed
main.getMetrics.func1({0x13d7220?, 0xc000800070?})
        /code/main.go:369 +0x31
github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run.func1()
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.9.0/worker_func.go:67 +0x97
created by github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run in goroutine 22
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.9.0/worker_func.go:48 +0x5c
```

**Comment by jmcgrath207** [comment]
Thanks for bring this up @jicki .

Does this happen immediately or crash loop after awhile.

Also could you share your values.yaml file so I can reproduce?
